"""add deposit orders

Revision ID: 0fdd67a900a5
Revises: 0153d2ad0e26
Create Date: 2026-09-20 08:18:22.981891

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fdd67a900a5"
down_revision: str | Sequence[str] | None = "0153d2ad0e26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("trade_id", sa.String(length=64), nullable=True),
        sa.Column("fiat_amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("expected_amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("receive_address", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PAID",
                "EXPIRED",
                "FAILED",
                name="depositstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("block_transaction_id", sa.String(length=128), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
        sa.UniqueConstraint("trade_id"),
    )
    op.create_index(op.f("ix_deposit_orders_status"), "deposit_orders", ["status"], unique=False)
    op.create_index(op.f("ix_deposit_orders_user_id"), "deposit_orders", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deposit_orders_user_id"), table_name="deposit_orders")
    op.drop_index(op.f("ix_deposit_orders_status"), table_name="deposit_orders")
    op.drop_table("deposit_orders")
    # ### end Alembic commands ###
